FROM openjdk:8-jdk-alpine
COPY ..
CMD ["java", "-jar", "discoveryServer.jar"]
CMD ["java", "-jar", "ticketGateway.jar"]
CMD ["java", "-jar", "create.jar"]
CMD ["java", "-jar", "read.jar"]
CMD ["java", "-jar", "readAll.jar"]
CMD ["java", "-jar", "update.jar"]
CMD ["java", "-jar", "delete.jar"]