apiVersion: v1
kind: Service
metadata:
  name: lb_nginx
  namespace: projectApp
  labels:
    app: nginx

spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer